version: '3.8'

services:
  netnexus:
    build: .
    container_name: netnexus
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
